--- 
abstract: Catalyst based application
author: 
  - Gerda Shank
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: BookDB
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::FillInForm: 0
  Catalyst::Plugin::Form::Processor: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7010
  Catalyst::View::TT: 0
  DBIx::Class: 0
  Form::Processor: 0
  Form::Processor::Model::DBIC: 0
  YAML: 0
version: 0.02
